"""initial schema

Revision ID: 40450f8b5d64
Revises:
Create Date: 2026-06-21 23:06:04.522956

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "40450f8b5d64"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "academic_courses",
        sa.Column("name", sa.String(length=240), nullable=False),
        sa.Column("semester", sa.String(length=40), nullable=False),
        sa.Column("credits", sa.Integer(), nullable=False),
        sa.Column("grade", sa.Float(), nullable=True),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("metadata", sa.JSON(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("legacy_key", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("legacy_key"),
    )
    op.create_table(
        "accounts",
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("institution", sa.String(length=160), nullable=False),
        sa.Column("account_type", sa.String(length=60), nullable=False),
        sa.Column("archived", sa.Boolean(), nullable=False),
        sa.Column("metadata", sa.JSON(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("legacy_key", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("legacy_key"),
    )
    op.create_table(
        "app_settings",
        sa.Column("key", sa.String(length=120), nullable=False),
        sa.Column("value", sa.JSON(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("legacy_key", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("key"),
        sa.UniqueConstraint("legacy_key"),
    )
    op.create_table(
        "automation_logs",
        sa.Column("source", sa.String(length=40), nullable=False),
        sa.Column("action", sa.String(length=120), nullable=False),
        sa.Column("endpoint", sa.String(length=240), nullable=False),
        sa.Column("result", sa.String(length=30), nullable=False),
        sa.Column("duration_ms", sa.Integer(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=160), nullable=True),
        sa.Column("entity_id", sa.String(length=36), nullable=True),
        sa.Column("error_code", sa.String(length=80), nullable=False),
        sa.Column("error_message", sa.String(length=500), nullable=False),
        sa.Column("metadata", sa.JSON(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("legacy_key", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("legacy_key"),
    )
    op.create_index(
        op.f("ix_automation_logs_idempotency_key"), "automation_logs", ["idempotency_key"], unique=False
    )
    op.create_index(op.f("ix_automation_logs_result"), "automation_logs", ["result"], unique=False)
    op.create_index(op.f("ix_automation_logs_source"), "automation_logs", ["source"], unique=False)
    op.create_table(
        "budgets",
        sa.Column("period", sa.String(length=7), nullable=False),
        sa.Column("income_target_cents", sa.Integer(), nullable=False),
        sa.Column("expense_limit_cents", sa.Integer(), nullable=False),
        sa.Column("savings_target_cents", sa.Integer(), nullable=False),
        sa.Column("category_limits", sa.JSON(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("legacy_key", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("legacy_key"),
        sa.UniqueConstraint("period", name="uq_budgets_period"),
    )
    op.create_index(op.f("ix_budgets_period"), "budgets", ["period"], unique=False)
    op.create_table(
        "car_logs",
        sa.Column("log_type", sa.String(length=40), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("odometer_km", sa.Integer(), nullable=True),
        sa.Column("amount_cents", sa.Integer(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("metadata", sa.JSON(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("legacy_key", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("legacy_key"),
    )
    op.create_index(op.f("ix_car_logs_date"), "car_logs", ["date"], unique=False)
    op.create_index(op.f("ix_car_logs_log_type"), "car_logs", ["log_type"], unique=False)
    op.create_table(
        "car_reminders",
        sa.Column("reminder_type", sa.String(length=60), nullable=False),
        sa.Column("title", sa.String(length=180), nullable=False),
        sa.Column("due_date", sa.Date(), nullable=True),
        sa.Column("due_odometer_km", sa.Integer(), nullable=True),
        sa.Column("recurrence", sa.String(length=40), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("metadata", sa.JSON(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("legacy_key", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("legacy_key"),
    )
    op.create_index(op.f("ix_car_reminders_reminder_type"), "car_reminders", ["reminder_type"], unique=False)
    op.create_table(
        "daily_reviews",
        sa.Column("review_date", sa.Date(), nullable=False),
        sa.Column("score", sa.Integer(), nullable=True),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("metadata", sa.JSON(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("legacy_key", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("legacy_key"),
        sa.UniqueConstraint("review_date", name="uq_daily_review_date"),
    )
    op.create_index(op.f("ix_daily_reviews_review_date"), "daily_reviews", ["review_date"], unique=False)
    op.create_table(
        "debts",
        sa.Column("entity", sa.String(length=180), nullable=False),
        sa.Column("direction", sa.String(length=20), nullable=False),
        sa.Column("current_amount_cents", sa.Integer(), nullable=False),
        sa.Column("due_date", sa.Date(), nullable=True),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("archived", sa.Boolean(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("legacy_key", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("legacy_key"),
    )
    op.create_index(op.f("ix_debts_entity"), "debts", ["entity"], unique=False)
    op.create_table(
        "events",
        sa.Column("title", sa.String(length=240), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("all_day", sa.Boolean(), nullable=False),
        sa.Column("recurrence", sa.String(length=40), nullable=False),
        sa.Column("location", sa.String(length=240), nullable=False),
        sa.Column("source", sa.String(length=40), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("metadata", sa.JSON(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("legacy_key", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("legacy_key"),
    )
    op.create_index(op.f("ix_events_starts_at"), "events", ["starts_at"], unique=False)
    op.create_table(
        "health_logs",
        sa.Column("log_type", sa.String(length=40), nullable=False),
        sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("value", sa.Float(), nullable=True),
        sa.Column("unit", sa.String(length=30), nullable=False),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.Column("metadata", sa.JSON(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("legacy_key", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("legacy_key"),
    )
    op.create_index(op.f("ix_health_logs_log_type"), "health_logs", ["log_type"], unique=False)
    op.create_index(op.f("ix_health_logs_recorded_at"), "health_logs", ["recorded_at"], unique=False)
    op.create_table(
        "import_batches",
        sa.Column("source", sa.String(length=60), nullable=False),
        sa.Column("payload_hash", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("counts", sa.JSON(), nullable=False),
        sa.Column("errors", sa.JSON(), nullable=False),
        sa.Column("committed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("legacy_key", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("legacy_key"),
        sa.UniqueConstraint("payload_hash"),
    )
    op.create_table(
        "inbox_messages",
        sa.Column("source", sa.String(length=40), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("external_id", sa.String(length=160), nullable=True),
        sa.Column("idempotency_key", sa.String(length=160), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("proposed_type", sa.String(length=30), nullable=False),
        sa.Column("proposed_payload", sa.JSON(), nullable=False),
        sa.Column("confirmed_entity_id", sa.String(length=36), nullable=True),
        sa.Column("metadata", sa.JSON(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("legacy_key", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("idempotency_key"),
        sa.UniqueConstraint("legacy_key"),
    )
    op.create_index(op.f("ix_inbox_messages_received_at"), "inbox_messages", ["received_at"], unique=False)
    op.create_index(op.f("ix_inbox_messages_source"), "inbox_messages", ["source"], unique=False)
    op.create_index(op.f("ix_inbox_messages_status"), "inbox_messages", ["status"], unique=False)
    op.create_table(
        "investments",
        sa.Column("investment_type", sa.String(length=80), nullable=False),
        sa.Column("institution", sa.String(length=160), nullable=False),
        sa.Column("amount_cents", sa.Integer(), nullable=False),
        sa.Column("as_of_date", sa.Date(), nullable=True),
        sa.Column("metadata", sa.JSON(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("legacy_key", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("legacy_key"),
    )
    op.create_table(
        "monthly_closures",
        sa.Column("module", sa.String(length=40), nullable=False),
        sa.Column("period", sa.String(length=7), nullable=False),
        sa.Column("closed", sa.Boolean(), nullable=False),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("checklist", sa.JSON(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("legacy_key", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("legacy_key"),
        sa.UniqueConstraint("module", "period", name="uq_monthly_closure"),
    )
    op.create_index(op.f("ix_monthly_closures_period"), "monthly_closures", ["period"], unique=False)
    op.create_table(
        "notes",
        sa.Column("note_type", sa.String(length=40), nullable=False),
        sa.Column("title", sa.String(length=240), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("note_date", sa.Date(), nullable=True),
        sa.Column("metadata", sa.JSON(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("legacy_key", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("legacy_key"),
    )
    op.create_index(op.f("ix_notes_note_date"), "notes", ["note_date"], unique=False)
    op.create_index(op.f("ix_notes_note_type"), "notes", ["note_type"], unique=False)
    op.create_table(
        "projects",
        sa.Column("name", sa.String(length=240), nullable=False),
        sa.Column("project_type", sa.String(length=50), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("target_date", sa.Date(), nullable=True),
        sa.Column("metadata", sa.JSON(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("legacy_key", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("legacy_key"),
    )
    op.create_table(
        "routines",
        sa.Column("routine_type", sa.String(length=40), nullable=False),
        sa.Column("name", sa.String(length=180), nullable=False),
        sa.Column("schedule", sa.JSON(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("metadata", sa.JSON(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("legacy_key", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("legacy_key"),
    )
    op.create_index(op.f("ix_routines_routine_type"), "routines", ["routine_type"], unique=False)
    op.create_table(
        "subscriptions",
        sa.Column("name", sa.String(length=180), nullable=False),
        sa.Column("amount_cents", sa.Integer(), nullable=False),
        sa.Column("category", sa.String(length=80), nullable=False),
        sa.Column("billing_day", sa.Integer(), nullable=False),
        sa.Column("frequency", sa.String(length=20), nullable=False),
        sa.Column("billing_month", sa.Integer(), nullable=True),
        sa.Column("payment_method", sa.String(length=80), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("legacy_key", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("legacy_key"),
    )
    op.create_table(
        "tasks",
        sa.Column("title", sa.String(length=240), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("priority", sa.String(length=20), nullable=False),
        sa.Column("due_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("source", sa.String(length=40), nullable=False),
        sa.Column("metadata", sa.JSON(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("legacy_key", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("legacy_key"),
    )
    op.create_index(op.f("ix_tasks_due_at"), "tasks", ["due_at"], unique=False)
    op.create_table(
        "tax_entries",
        sa.Column("entry_type", sa.String(length=40), nullable=False),
        sa.Column("period", sa.String(length=7), nullable=False),
        sa.Column("date", sa.Date(), nullable=True),
        sa.Column("concept", sa.String(length=240), nullable=False),
        sa.Column("subtotal_cents", sa.Integer(), nullable=False),
        sa.Column("tax_cents", sa.Integer(), nullable=False),
        sa.Column("withholding_isr_cents", sa.Integer(), nullable=False),
        sa.Column("withholding_iva_cents", sa.Integer(), nullable=False),
        sa.Column("total_cents", sa.Integer(), nullable=False),
        sa.Column("metadata", sa.JSON(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("legacy_key", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("legacy_key"),
    )
    op.create_index(op.f("ix_tax_entries_entry_type"), "tax_entries", ["entry_type"], unique=False)
    op.create_index(op.f("ix_tax_entries_period"), "tax_entries", ["period"], unique=False)
    op.create_table(
        "uploaded_files",
        sa.Column("original_name", sa.String(length=255), nullable=False),
        sa.Column("stored_name", sa.String(length=255), nullable=False),
        sa.Column("relative_path", sa.String(length=500), nullable=False),
        sa.Column("content_type", sa.String(length=120), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("purpose", sa.String(length=60), nullable=False),
        sa.Column("metadata", sa.JSON(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("legacy_key", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("legacy_key"),
        sa.UniqueConstraint("sha256"),
    )
    op.create_table(
        "debt_movements",
        sa.Column("debt_id", sa.String(length=36), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("kind", sa.String(length=40), nullable=False),
        sa.Column("amount_cents", sa.Integer(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("due_date", sa.Date(), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("legacy_key", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["debt_id"], ["debts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("legacy_key"),
    )
    op.create_index(op.f("ix_debt_movements_date"), "debt_movements", ["date"], unique=False)
    op.create_index(op.f("ix_debt_movements_debt_id"), "debt_movements", ["debt_id"], unique=False)
    op.create_table(
        "tax_documents",
        sa.Column("document_kind", sa.String(length=40), nullable=False),
        sa.Column("period", sa.String(length=7), nullable=False),
        sa.Column("document_date", sa.Date(), nullable=True),
        sa.Column("uuid", sa.String(length=80), nullable=True),
        sa.Column("issuer_rfc", sa.String(length=20), nullable=False),
        sa.Column("receiver_rfc", sa.String(length=20), nullable=False),
        sa.Column("subtotal_cents", sa.Integer(), nullable=False),
        sa.Column("tax_transferred_cents", sa.Integer(), nullable=False),
        sa.Column("tax_withheld_cents", sa.Integer(), nullable=False),
        sa.Column("total_cents", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("source_hash", sa.String(length=64), nullable=False),
        sa.Column("file_id", sa.String(length=36), nullable=True),
        sa.Column("summary", sa.JSON(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("legacy_key", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["file_id"],
            ["uploaded_files.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("legacy_key"),
        sa.UniqueConstraint("source_hash"),
        sa.UniqueConstraint("uuid"),
    )
    op.create_index(op.f("ix_tax_documents_period"), "tax_documents", ["period"], unique=False)
    op.create_index(
        "ix_tax_documents_period_kind", "tax_documents", ["period", "document_kind"], unique=False
    )
    op.create_table(
        "transactions",
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("type", sa.String(length=20), nullable=False),
        sa.Column("category", sa.String(length=80), nullable=False),
        sa.Column("name", sa.String(length=240), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("amount_cents", sa.Integer(), nullable=False),
        sa.Column("expense_nature", sa.String(length=30), nullable=False),
        sa.Column("source", sa.String(length=40), nullable=False),
        sa.Column("source_hash", sa.String(length=128), nullable=True),
        sa.Column("account_id", sa.String(length=36), nullable=True),
        sa.Column("metadata", sa.JSON(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("legacy_key", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("legacy_key"),
        sa.UniqueConstraint("source_hash"),
    )
    op.create_index(op.f("ix_transactions_category"), "transactions", ["category"], unique=False)
    op.create_index(op.f("ix_transactions_date"), "transactions", ["date"], unique=False)
    op.create_index("ix_transactions_date_type", "transactions", ["date", "type"], unique=False)
    op.create_index(op.f("ix_transactions_type"), "transactions", ["type"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_transactions_type"), table_name="transactions")
    op.drop_index("ix_transactions_date_type", table_name="transactions")
    op.drop_index(op.f("ix_transactions_date"), table_name="transactions")
    op.drop_index(op.f("ix_transactions_category"), table_name="transactions")
    op.drop_table("transactions")
    op.drop_index("ix_tax_documents_period_kind", table_name="tax_documents")
    op.drop_index(op.f("ix_tax_documents_period"), table_name="tax_documents")
    op.drop_table("tax_documents")
    op.drop_index(op.f("ix_debt_movements_debt_id"), table_name="debt_movements")
    op.drop_index(op.f("ix_debt_movements_date"), table_name="debt_movements")
    op.drop_table("debt_movements")
    op.drop_table("uploaded_files")
    op.drop_index(op.f("ix_tax_entries_period"), table_name="tax_entries")
    op.drop_index(op.f("ix_tax_entries_entry_type"), table_name="tax_entries")
    op.drop_table("tax_entries")
    op.drop_index(op.f("ix_tasks_due_at"), table_name="tasks")
    op.drop_table("tasks")
    op.drop_table("subscriptions")
    op.drop_index(op.f("ix_routines_routine_type"), table_name="routines")
    op.drop_table("routines")
    op.drop_table("projects")
    op.drop_index(op.f("ix_notes_note_type"), table_name="notes")
    op.drop_index(op.f("ix_notes_note_date"), table_name="notes")
    op.drop_table("notes")
    op.drop_index(op.f("ix_monthly_closures_period"), table_name="monthly_closures")
    op.drop_table("monthly_closures")
    op.drop_table("investments")
    op.drop_index(op.f("ix_inbox_messages_status"), table_name="inbox_messages")
    op.drop_index(op.f("ix_inbox_messages_source"), table_name="inbox_messages")
    op.drop_index(op.f("ix_inbox_messages_received_at"), table_name="inbox_messages")
    op.drop_table("inbox_messages")
    op.drop_table("import_batches")
    op.drop_index(op.f("ix_health_logs_recorded_at"), table_name="health_logs")
    op.drop_index(op.f("ix_health_logs_log_type"), table_name="health_logs")
    op.drop_table("health_logs")
    op.drop_index(op.f("ix_events_starts_at"), table_name="events")
    op.drop_table("events")
    op.drop_index(op.f("ix_debts_entity"), table_name="debts")
    op.drop_table("debts")
    op.drop_index(op.f("ix_daily_reviews_review_date"), table_name="daily_reviews")
    op.drop_table("daily_reviews")
    op.drop_index(op.f("ix_car_reminders_reminder_type"), table_name="car_reminders")
    op.drop_table("car_reminders")
    op.drop_index(op.f("ix_car_logs_log_type"), table_name="car_logs")
    op.drop_index(op.f("ix_car_logs_date"), table_name="car_logs")
    op.drop_table("car_logs")
    op.drop_index(op.f("ix_budgets_period"), table_name="budgets")
    op.drop_table("budgets")
    op.drop_index(op.f("ix_automation_logs_source"), table_name="automation_logs")
    op.drop_index(op.f("ix_automation_logs_result"), table_name="automation_logs")
    op.drop_index(op.f("ix_automation_logs_idempotency_key"), table_name="automation_logs")
    op.drop_table("automation_logs")
    op.drop_table("app_settings")
    op.drop_table("accounts")
    op.drop_table("academic_courses")
    # ### end Alembic commands ###
